export const SOURCES = [
    {
        title: 'Map of the terrestrial ecosystems of Myanmar, Version 1.0',
        AccessDate: '19/03/2024',
        Analyst: 'Naema_GrosDubois',
        YearRepresented: '2020',
        ShortName: 'unsw_myan_eco_2020',
        Abstract:
            'This map of the terrestrial ecosystems of Myanmar was developed using a supervised learning approach to classify earth observation data and other geospatial datasets into broad mappable units, which was then split into the ecosystem types defined by the IUCN Red List of Ecosystems of Myanmar project. The shapefile presents the hierarchical ecosystem typology for Myanmar, including attributes that indicate ecosystems grouped at the Functional Ecotype and Ecosystem Type level of the Myanmar ecosystem typology.',
        Description:
            ' This dataset was produced by first developing a training set of 63124 point observations map classes that could be related to ecosystem types. The distribution of each map class was modelled using a random forest classifier and 89 covariate layers developed from data acquired in 2018. Each mappable unit was then compiled into a single map and a variety of expert rules were applied to split the map into ecosystem types defined by the IUCN Red List of Ecosystems of Myanmar ecosystem typology. Additional ecosystem types, including mudflats, aerobic caves, and glacial lakes were added from freely available published data. The final dataset thus depicts the modelled distribution of 52 terrestrial ecosystem types mapped at 90-m resolution. Further details of the mapping process are available in the IUCN Red List of Ecosystems of Myanmar report (Murray et al. 2020) and in an associated scientific paper (Duncan et al., in prep)',
        Provider:
            'University of New South Wales; James Cook University; Wildlife Conservation Society; IUCN Commission on Ecosystem Management; NSW Department of Planning Industry and Environment',
        Citation:
            'Murray, N.J., Keith, D.A., Tizard, R., Duncan, A., Htut, W.T., Hlaing, N., Oo, A.H., Ya, K.Z., Grantham, H. (2020) Map of the Terrestrial Ecosystems of Myanmar, Version 1.0. Figshare.',
        PublishedYear: '2020',
        Contact: 'Nicholas Murray',
        email: 'nicholas.murray@jcu.edu.au',
        License: 'CC BY 4.0',
        LicenseURL: 'https://creativecommons.org/licences/by/4.0/',
        URL: 'https://figshare.com/articles/dataset/Map_of_the_terrestrial_ecosystems_of_Myanmar_Version_1_0/12364067',
        DOI: 'https://doi.org/10.6084/m9.figshare.12364067',
    },
    {
        title: '',
        AccessDate: '',
        Analyst: '',
        YearRepresented: '',
        ShortName: '',
        Abstract: '',
        Provider: '',
        Citation: '',
        PublishedYear: '',
        Contact: '',
        email: '',
        License: '',
        LicenseURL: '',
        URL: '',
        DOI: '',
    },
    {
        title: '',
        AccessDate: '',
        Analyst: '',
        YearRepresented: '',
        ShortName: '',
        Abstract: '',
        Provider: '',
        Citation: '',
        PublishedYear: '',
        Contact: '',
        email: '',
        License: '',
        LicenseURL: '',
        URL: '',
        DOI: '',
    },
];
